### ISSUE TITLE
Crash on launch on iOS 15.6

### ISSUE THREAD

**Issue by jaswant0605** [MirrorFly/MirrorFly-iOS-Sample#7]
![Screenshot 2022-08-08 at 5 16 56 PM](https://user-images.githubusercontent.com/31925211/183411128-4d97f48f-2b49-46d6-abb9-8455228e2ebf.png)

**Comment by lalkrishna** [comment]
Getting same crash for me as well. 

Thread 1: "Realm path must not be empty"

**Comment by ShruthiD99** [comment]
To resolve "Realm path must not be empty" error, your CONTAINER_ID must be set to your app group ID

**Comment by jaswant0605** [comment]
It’s the same. Can we get on a call?

**Comment by ShruthiD99** [comment]
Sure I'll talk to my team to arrange a call. Meanwhile can you try setting the below two values to CONTAINER_ID after ChatSDK.Builder initialization and check.
1. FlyConstants.suitename = CONTAINER_ID
2. FlyDefaults.appGroupContainerID = CONTAINER_ID

**Comment by jaswant0605** [comment]
Sure, will do that.
